/************************************************************
FLAG
************************************************************/

$flag-gutters: 4 !default;

.flag {

  display: inline-flex;
  vertical-align: middle;

  &\/item {
    display: flex;
    flex-grow: 0;
    flex-basis: auto;
    align-items: center;
    width: auto;
  }

  /******************************
  GUTTER
  ******************************/

	&-gutter {
		@while $flag-gutters > 0 {
			&\:#{$flag-gutters} {
				.flag\/item {
          margin-right: $flag-gutters * 1rem / 2;
          &:last-child {
            margin-right: 0;
          }
        }
			}
			$flag-gutters: $flag-gutters - 1;
		}
	}
}
