/************************************************************
MARKUP
************************************************************/

.markup {
  h1,h2,h3,h4,h5,h6 {
    color: var(--black);
  	font-weight: var(--bold);
    line-height: 1.25;
  	&:first-child {
  		margin-top: 0;
  	}
  	&:last-child {
  		margin-bottom: 0;
  	}
  }
  h1 {
  	margin-top: var(--u9);
  	margin-bottom: var(--u6);
  }
  h2 {
  	margin-top: var(--u9);
  	margin-bottom: var(--u6);
  }
  h3 {
  	margin-top: var(--u9);
  	margin-bottom: var(--u6);
  }
  h4 {
  	margin-top: var(--u9);
  	margin-bottom: var(--u6);
  }
  h5 {
  	margin-top: var(--u9);
  	margin-bottom: var(--u4);
  }
  h6 {
  	margin-top: var(--u7);
  	margin-bottom: var(--u4);
  }
  ol, ul {
  	margin: 0;
  	margin-left: var(--u5);
  	margin-bottom: var(--u6);
  }
  li {
  	padding-left: var(--u0);
  }
  ol {
  	list-style-type: decimal;
  }
  ul {
  	list-style-type: disc;
  }
}
