/************************************************************
FORM
************************************************************/

:root {
  --form-label-weight: var(--medium);
  --form-label-size: var(--tiny);

  --form-field-height: var(--u9);
  --form-field-border: var(--border);
  --form-field-fill: var(--white);
  --form-field-checkbox-fill: var(--blue);
  --form-field-color: var(--black);
  --form-field-radius: .25rem;
  --form-field-padding-left: 1rem;

  --form-disabled-fill: var(--grey-l5);
  --form-disabled-color: var(--grey-d1);
  --form-disabled-opacity: 1;

  --form-success-border-color: var(--green);
  --form-alert-border-color: var(--orange);
  --form-warning-border-color: var(--red);
}

.form {

  /******************************
  FIELDSET
  ******************************/

  &\/item {
    position: relative;
    display: block;
    margin-bottom: var(--u4);
    &:last-child {
      margin-bottom: 0;
    }
    &:after {
      content: "";
      display: table !important;
      clear: both !important;
    }
  }
  &\/help {
    padding-top: var(--u1);
    font-size: var(--micro);
    color: var(--default-color);
    &-item {
      // States
      &.is-success {
        color: var(--form-success-border-color);
      }
      &.is-alert {
        color: var(--form-alert-border-color);
      }
      &.is-warning {
        color: var(--form-warning-border-color);
      }
    }
  }
}

.field {
  &\:slide {
    position: relative;
    input {
      min-height: 4rem;
      padding: 1.75rem 0 1rem var(--form-field-padding-left);

      &:placeholder-shown ~ label {
        position: absolute;
        top: 1.25rem;
        left: 1rem;
        margin: 0;
        padding: 0;
        font-size: var(--body);
        color: var(--grey-d2);
        pointer-events: none;
      }
      &:not(:placeholder-shown) ~ label {
        position: absolute;
        top: .25rem;
        left: .5rem;
        margin: 0;
        padding: 0;
        font-size: .75rem;
        color: var(--grey-d1);
        z-index: 1;
        pointer-events: none;
      }
      & ~ label, &:focus ~ label {
        position: absolute;
        top: .25rem;
        left: .5rem;
        margin: 0;
        padding: 0;
        font-size: .75rem;
        color: var(--grey-d1);
        z-index: 1;
        pointer-events: none;

        @media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
          /* IE10+ CSS styles go here */
          position: absolute;
          top: .25rem;
          left: .5rem;
          margin: 0;
          padding: 0;
          font-size: 13px;
          color: var(--grey-d1);
          z-index: 1;
          pointer-events: none;
        }
      }

      /* states */
      &.is-success:not(:placeholder-shown) ~ label {
        color: var(--form-success-border-color);
      }
      &.is-alert:not(:placeholder-shown) ~ label {
        color: var(--form-alert-border-color);
      }
      &.is-warning:not(:placeholder-shown) ~ label {
        color: var(--form-warning-border-color);
      }
    }
  }
  &\:slide-select {
    position: relative;
    width: 100%;
    max-width: 300px;

    select {
      min-height: 4rem;
    }

    &:after {
      content: '\f107';
      position: absolute;
      top: 2rem;
      transform: translateY(-50%);
      right: 1.25rem;
      display: block;
      font-family: 'Font Awesome 5 Free', 'Font Awesome 5 Pro';
      font-style: normal;
      font-size: 1.25rem;
      font-variant: normal;
      text-rendering: auto;
      font-weight: bold;
      line-height: 1;
      -moz-osx-font-smoothing: grayscale;
      -webkit-font-smoothing: antialiased;
      color: var(--black);
      pointer-events: none;
    }
  }

  &\:checkbox {
    display: block;
    position: relative;
    padding: 0;
    padding-left: var(--u7);
    cursor: pointer;
    padding-bottom: 0 !important;
    font-size: var(--tiny) !important;
    font-weight: var(--regular) !important;
    line-height: 1.5 !important;

    input {
      display: none;
      &:checked ~ .field\/indicator {
        background: var(--form-field-checkbox-fill);
        border-color: var(--form-field-checkbox-fill);
        &:after {
          display: block;
        }
      }
      &:disabled {
        & ~ .field\/indicator {
          background: var(--form-disabled-fill);
          border-color: var(--border-color);
          opacity: var(--form-disabled-opacity);
          pointer-events: none;
          &:after {
            border-color: var(--black);
          }
        }
      }
    }
    .field\/indicator {
      position: absolute;
      top: 0;
      left: 0;
      height: var(--u5);
      width: var(--u5);
      border-radius: var(--form-field-radius);
      border: var(--border);
      background: white;

      &:after {
        content: '';
        display: none;
        position: absolute;
        left: .40rem;
        top: .07rem;
        width: .4rem;
        height: .75rem;
        border: solid white;
        border-width: 0 .15rem .15rem 0;
        transform: rotate(45deg);
      }
    }
  }

  &\:toggle {
    display: inline-block;
    position: relative;
    width: 56px;
    height: 28px;

    .field\/indicator {
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      background-color: var(--grey-l4);
      transition: .4s;
      border-radius: 100px;
      cursor: pointer;

      &:before {
        content: "";
        position: absolute;
        left: 4px;
        bottom: 4px;
        width: 20px;
        height: 20px;
        background-color: #fff;
        border-radius: 100px;
        transition: .2s;
      }
    }

    input {
      display:none;
    }
    input:checked + .field\/indicator {
      background-color: var(--lime);
    }
    input:checked + .field\/indicator:before {
      transform: translateX(28px);
    }
  }


  &\:radio {
    display: block;
    position: relative;
    padding: 0;
    padding-left: var(--u7);
    cursor: pointer;
    padding-bottom: 0 !important;
    font-size: var(--tiny) !important;
    font-weight: var(--regular) !important;
    line-height: 1.5 !important;

    input {
      display: none;
      &:checked ~ .field\/indicator {
        &:after {
          display: block;
          background: var(--form-field-checkbox-fill);
        }
      }
      &:disabled {
        & ~ .field\/indicator {
          background: var(--form-disabled-fill);
          opacity: var(--form-disabled-opacity);
          pointer-events: none;
          &:after {
            background: black;
          }
        }
      }
    }
    .field\/indicator {
      display: flex;
      align-items: center;
      justify-content: center;
      position: absolute;
      top: 0;
      left: 0;
      width: var(--u5);
      height: var(--u5);
      border-radius: 100px;
      border: var(--border);
      background: white;
      &:after {
        position: absolute;
        content: '';
        display: none;
        width: .75rem;
        height: .75rem;
        border-radius: 100px;
      }
    }
  }

  &\:select {
    position: relative;
    width: 100%;
    max-width: 300px;

    &:after {
      content: '\f107';
      position: absolute;
      top: 1.55rem;
      transform: translateY(-50%);
      right: 1.25rem;
      display: block;
      font-family: 'Font Awesome 5 Free', 'Font Awesome 5 Pro';
      font-style: normal;
      font-size: 1.25rem;
      font-variant: normal;
      text-rendering: auto;
      font-weight: bold;
      line-height: 1;
      -moz-osx-font-smoothing: grayscale;
      -webkit-font-smoothing: antialiased;
      color: var(--black);
      pointer-events: none;
    }
  }

  &\:icons {
    position: relative;
    input:not([type="submit"]) {
      padding-left: var(--form-field-height);
      padding-right: var(--form-field-height);
      &:focus {
        & ~ .field\/icon {
          color: var(--form-field-checkbox-fill);
        }
        & ~ .field\/text {
          color: var(--form-field-checkbox-fill);
        }
      }
    }
    .field\/icon {
      display: flex;
      position: absolute;
      top: 0;
      width: var(--form-field-height);
      height: 100%;
      align-items: center;
      justify-content: center;
      transition: var(--transition);
    }
    .field\/text {
      display: flex;
      position: absolute;
      top: 0;
      left: auto;
      right: var(--u5);
      height: 100%;
      align-items: center;
      font-weight: var(--regular);
      transition: var(--transition);
    }
  }

  &\:file {
    cursor: pointer;
  }
}

/******************************
LABEL
******************************/

label {
  display: block;
  position: relative;
  padding-top: var(--u1);
  padding-bottom: var(--u1);
  font-size: var(--form-label-size);
  font-weight: var(--form-label-weight);
  color: var(--black);
  line-height: 1.55;
  transition: var(--transition);
}

.label:required {
  &:after {
    content: '*';
    position: relative;
    display: inline-block;
    top: -.3rem;
    left: .2rem;
    color: var(--red);
  }
}

/******************************
FIELD
******************************/

input {
  display: block;
  position: relative;

  &:not([type="submit"]) {
    width: 100%;
    max-width: 300px;
    height: var(--form-field-height);
    padding-left: var(--form-field-padding-left);
    background: var(--form-field-fill);
    color: var(--form-field-color);
    font-family: var(--font-family);
    font-size: var(--font-size);
    border: var(--form-field-border);
    border-radius: var(--form-field-radius);
    outline: 0;
    appearance: none;
    transition: var(--transition);

    &:focus {
      border-color: var(--grey-l2);
    }
    &:disabled {
      background: var(--form-disabled-fill);
      color: var(--form-disabled-color);
      opacity: var(--form-disabled-opacity);
      pointer-events: none;
    }

    /* states */
    &.is-success {
      border-color: var(--form-success-border-color);
    }
    &.is-alert {
      border-color: var(--form-alert-border-color);
    }
    &.is-warning {
      border-color: var(--form-warning-border-color);
    }
  }
  &[type="password"] {
    font-size: 22px;
  }
  &[type="file"] {
    display: none;
  }
}

// vendor reset styling
input[type=number]::-webkit-inner-spin-button,
input[type=number]::-webkit-outer-spin-button {
  -webkit-appearance: none;
}
input[type=number] {
  -moz-appearance:textfield;
}
input[type=submit] {
  appearance: none;
}

textarea {
  display: block;
  position: relative;
  width: 100%;
  max-width: 500px;
  min-height: var(--u15);
  padding: var(--u4);
  background: white;
  border: var(--form-field-border);
  border-radius: var(--form-field-radius);
  color: var(--form-field-color);
  font-family: var(--font-family);
  font-size: var(--font-size);
  outline: 0;
  appearance: none;
  transition: var(--transition);

  &:focus {
    border-color: var(--grey-l2);
  }
  &:disabled {
    background: var(--form-disabled-fill);
    opacity: var(--form-disabled-opacity);
    pointer-events: none;
  }

  /* states */
  &.is-success {
    border-color: var(--form-success-border-color);
  }
  &.is-alert {
    border-color: var(--form-alert-border-color);
  }
  &.is-warning {
    border-color: var(--form-warning-border-color);
  }
}

select {
  display: inline-block;
  width: 100%;
  height: var(--form-field-height);
  padding-left: var(--form-field-padding-left);
  outline: 0;
  border: var(--border);
  border-radius: var(--form-field-radius);
  appearance: none;
  background: white;
  color: var(--form-field-color);
  font-size: var(--font-size);
  cursor: pointer;

  &:hover, &:focus {
    color: #000;
  }
  &:hover ~ .form\/arrow,
  &:focus ~ .form\/arrow {
    border-color: #000;
  }
  &:disabled {
    background: var(--form-disabled-fill);
    opacity: var(--form-disabled-opacity);
    pointer-events: none;
    ~ .form\/arrow {
      border-color: var(--form-disabled-fill);
    }
  }

  /* states */
  &.is-success {
    border-color: var(--form-success-border-color);
  }
  &.is-alert {
    border-color: var(--form-alert-border-color);
  }
  &.is-warning {
    border-color: var(--form-warning-border-color);
  }
}
select::-ms-expand {
  display: none;
}
