/************************************************************
FORM
************************************************************/

:root {
  --form-label-weight: var(--body);
  --form-label-size: var(--tiny);

  --form-success-color: var(--green);
  --form-alert-color: var(--orange);
  --form-warning-color: var(--red);
}

.form {

  /******************************
  FIELDSET
  ******************************/

  &\/item {
    position: relative;
    display: block;
    margin-bottom: var(--u4);
    &:last-child {
      margin-bottom: 0;
    }
    &:after {
      content: "";
      display: table !important;
      clear: both !important;
    }
  }
  &\/label {
    &\:required {
      &:after {
        content: '*';
        position: relative;
        display: inline-block;
        top: -.3rem;
        left: .2rem;
        color: var(--red);
      }
    }
  }
  &\/message {
    padding-top: var(--u1);
    font-size: var(--micro);
    color: var(--default-color);
    &-item {
      // States
      &.is-success {
        color: var(--form-success-color);
      }
      &.is-alert {
        color: var(--form-alert-color);
      }
      &.is-warning {
        color: var(--form-warning-color);
      }
    }
  }
}
