baseURL= "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "SlashGo"

[menu]

  [[menu.docs]]
    name = "Button"
    url = "/button/"
    weight = -100

  [[menu.docs]]
    name = "Table"
    url = "/table/"
    weight = -100

  [[menu.docs]]
    name = "Crumb"
    url = "/crumb/"
    weight = -100

  [[menu.docs]]
    name = "List"
    url = "/list/"
    weight = -100

  [[menu.docs]]
    name = "Icon"
    url = "/icon/"
    weight = -100
