/************************************************************
DROPDOWN
************************************************************/

:root {
  --dropdown-body-fill: var(--white);
  --dropdown-body-radius: var(--radius);
  --dropdown-body-shadow: 0px 0px 0px 1px var(--border-color);

  --dropdown-item-padding: .5rem;
  --dropdown-item-color: var(--grey-d1);
  --dropdown-item-hover-color: var(--grey-d2);
  --dropdown-item-hover-fill: var(--grey-l5);
  --dropdown-item-active-fill: var(--grey-l4);
}

.#{$prefix}dropdown {
  display: inline-block;
  position: relative;

  &.is-active {
    .dropdown\/container {
      visibility: visible;
      opacity: 1;
    }
  }

  /******************************
  POSITION
  ******************************/

  &-position {
    &\:center {
      .dropdown\/container {
        left: 50%;
        transform: translateX(-50%);
      }
    }
    &\:right {
      .dropdown\/container {
        right: 0;
      }
    }
    &\:top {
      .dropdown\/container {
        top: auto;
        bottom: 100%;
        padding: 0;
        padding-bottom: 10px;
      }
      &-center {
        .dropdown\/container {
          top: auto;
          bottom: 100%;
          left: 50%;
          padding: 0;
          padding-bottom: 10px;
          transform: translateX(-50%);
        }
      }
      &-right {
        .dropdown\/container {
          top: auto;
          right: 0;
          bottom: 100%;
          padding: 0;
          padding-bottom: 10px;
        }
      }
    }
  }

  /******************************
  CHILD ELEMENTS
  ******************************/

  &\/container {
    visibility: hidden;
    position: absolute;
    top: 100%;
    margin: 0;
    padding-top: 10px;
    transition: var(--transition);
    opacity: 0;
    z-index: 10;
  }
}
